application: engine
version: 3
runtime: python27
api_version: 1
threadsafe: yes
module: default

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: API_main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest  
